Cope with zero-line baseline file

diff --git a/eyeball b/eyeball
--- a/eyeball
+++ b/eyeball
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 if [ "$#" -ne 2 ]; then
     echo "Usage: eyeball <program> <outputfile>"
     exit 1
@@ -9,27 +11,33 @@ EXPECTED_FILE=$FILE
 ACTUAL_FILE=$FILE.eyeball
 
 DIFF="git --no-pager diff --color-words --no-index"
+#DIFF="diff"
 DIFF_COMMAND_LINE="$DIFF $EXPECTED_FILE $ACTUAL_FILE"
 # colordiff $ACTUAL_FILE $EXPECTED_FILE
 
+# Run the command and output to the 'expected' file if it doesn't already exist, then exit
 if [ ! -f $EXPECTED_FILE ]; then
     eval $COMMAND 2>&1 | tee $EXPECTED_FILE
     echo ">>> eyeball: Created '$EXPECTED_FILE'"
     exit 0
 fi
 
-eval $COMMAND 2>&1 | tee $ACTUAL_FILE 
+# Run the command and output to the 'actual' file
+$COMMAND 2>&1 | tee $ACTUAL_FILE 
 
 ACTUAL_FILE_LINES=$(cat $ACTUAL_FILE | wc -l | xargs)
 EXPECTED_FILE_LINES=$(cat $EXPECTED_FILE | wc -l | xargs)
 
 # Don't show diff if actual output line count is less than a tenth of expected output line count
-let TOO_FEW_OUTPUT_LINES=`bc <<< "scale=100; ($ACTUAL_FILE_LINES / $EXPECTED_FILE_LINES) < 0.1"`
-if [ $TOO_FEW_OUTPUT_LINES == 1 ] ; then
-  echo ">>> eyeball: Output much shorter than expected (expected $EXPECTED_FILE_LINES lines, saw $ACTUAL_FILE_LINES lines). Not showing diff."
-  echo ">>> eyeball: To see the diff run '$DIFF_COMMAND_LINE'"
-  echo ">>> eyeball: Run 'eyeball-update $2' to update expected output."
-  exit 1
+if [ $EXPECTED_FILE_LINES -ne 0 ] ; then
+  let TOO_FEW_OUTPUT_LINES=`bc <<< "scale=100; ($ACTUAL_FILE_LINES / $EXPECTED_FILE_LINES) < 0.1"`
+  if [ $TOO_FEW_OUTPUT_LINES == 1 ] ; then
+    echo ">>> eyeball: Output much shorter than expected (expected $EXPECTED_FILE_LINES lines, saw $ACTUAL_FILE_LINES lines). Not showing diff."
+    echo ">>> eyeball: To see the diff run '$DIFF_COMMAND_LINE'"
+    echo ">>> eyeball: Run 'eyeball-update $2' to update expected output."
+    echo ">>> eyeball: FAIL"
+    exit 1
+  fi
 fi
 
 echo ">>> eyeball: Running '$DIFF_COMMAND_LINE'"
